### ISSUE TITLE
How to properly close/reset camera?

### ISSUE THREAD

**Issue by Soleildanh** [python-zwoasi/python-zwoasi#10] opened 2019-04-16 17:56 UTC
I am developing a GUI that interacts with the zwoasi. I am unsure how to close the camera properly. If I do camera.close() and try to reconnect with camera = asi.Camera(camera_id) like in the example script I get the following error:
raise ZWO_Error('Library already initialized')
zwoasi.ZWO_Error: Library already initialized

**Comment by stevemarple** [comment] 2019-04-21 15:23
Can you please attach the code where you call `camera = asi.Camera(camera_id)`. Initializing the library is meant to be independent of opening a camera device. Can you please also indicate the python version and zwoasi version you are using?

I don't have access to a ZWO camera any more so I shall need some help from someone who does in order to properly solve any problems.

**Comment by Soleildanh** [comment] 2019-04-26 22:42
I am using Python 2.7, the current zwoasi, and the camera is a ASI120MC. The file attached is a handler I wrote using your example. I'm unsure how to properly close the camera device.
[ZWO_Handler.txt](https://github.com/stevemarple/python-zwoasi/files/3123186/ZWO_Handler.txt)

**Comment by stevemarple** [comment] 2019-04-28 21:03
Thanks for that information. I can see that the problem is in the `connectHardware()` function. It calls `zwoasi.init()` every time, but `zwoasi.init()` is intended to be called only once, after the ZWOASI library has been imported.

You should probably move the call to `zwoasi.init()` to somewhere where it will only be called once. Otherwise you'll need to remember inside your `connectHardware()` function that the library has been initialized and not attempt to do so again.

**Comment by Soleildanh** [comment] 2019-05-01 17:21
When you said I call zwoasi.init() every time, are you referring to the line asi.init(args.filename), or self.ZWO = asi.Camera(camera_id)? Is there a method that I can call to check whether or not zwoasi.init() has already been called? And if I were to call self.ZWO.close(), what would be the proper method to reconnect with the camera again?

**Comment by iromero91** [comment] 2021-06-23 15:27
This was fixed by #17

**Closed by iromero91** 2021-06-23 15:27 UTC
